// Million Mind — CSV Importer (Node port)
// =========================================
// Converts a Powerball CSV file in the format
//
//     Powerball,M,D,YYYY,n1,n2,n3,n4,n5,powerball,multiplier
//
// (whites in any order; we sort ascending) into:
//
//   1. supabase/seed/full_history.sql  — INSERT statements ready for psql -f
//   2. supabase/seed/full_history.csv  — normalized CSV with our schema columns
//
// USAGE (from repo root):
//
//   node supabase/scripts/import_csv.mjs                              # auto-finds ~/Downloads/powerball.csv
//   node supabase/scripts/import_csv.mjs path/to/powerball.csv
//   node supabase/scripts/import_csv.mjs --input ... --sql ... --csv ...
//
// Then load into local Postgres:
//
//   psql "$DATABASE_URL" -f supabase/seed/full_history.sql

import fs from "node:fs";
import os from "node:os";
import path from "node:path";

function parseArgs(argv) {
  const args = { input: null, sql: null, csv: null };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--input") args.input = argv[++i];
    else if (a === "--sql") args.sql = argv[++i];
    else if (a === "--csv") args.csv = argv[++i];
    else if (!a.startsWith("--") && !args.input) args.input = a;
  }
  return args;
}

function resolveInput(provided) {
  if (provided) return path.resolve(provided);
  const home = path.join(os.homedir(), "Downloads", "powerball.csv");
  if (fs.existsSync(home)) return home;
  console.error(
    "ERROR: no input CSV found. Pass it as the first arg, --input, or place it at ~/Downloads/powerball.csv.",
  );
  process.exit(1);
}

function parseCsvLine(line) {
  // Simple CSV parsing — no quoted fields in this dataset.
  return line.split(",").map((c) => c.trim());
}

function parseRow(raw, lineno) {
  if (raw.length < 10) {
    console.log(`  line ${lineno}: skipped (only ${raw.length} columns)`);
    return null;
  }

  // Tolerate either "Powerball,M,D,YYYY,..." or "M,D,YYYY,..."
  const cells =
    raw[0].toLowerCase().startsWith("powerball") ? raw.slice(1) : raw;

  if (cells.length < 9) {
    console.log(`  line ${lineno}: skipped (only ${cells.length} numeric cells)`);
    return null;
  }

  const month = Number(cells[0]);
  const day = Number(cells[1]);
  const year = Number(cells[2]);
  if (!Number.isInteger(month) || !Number.isInteger(day) || !Number.isInteger(year)) {
    console.log(`  line ${lineno}: skipped — bad date components`);
    return null;
  }

  const whites = cells.slice(3, 8).map(Number);
  if (whites.some((n) => !Number.isInteger(n))) {
    console.log(`  line ${lineno}: skipped — non-integer white ball`);
    return null;
  }
  whites.sort((a, b) => a - b);

  const powerball = Number(cells[8]);
  if (!Number.isInteger(powerball)) {
    console.log(`  line ${lineno}: skipped — non-integer powerball`);
    return null;
  }

  let multiplier = Number(cells[9] ?? "1");
  if (!Number.isFinite(multiplier) || multiplier < 1) multiplier = 1;
  multiplier = Math.max(1, Math.min(10, Math.trunc(multiplier)));

  if (whites.some((n) => n < 1 || n > 69)) {
    console.log(`  line ${lineno}: skipped — white ball out of range ${JSON.stringify(whites)}`);
    return null;
  }
  if (powerball < 1 || powerball > 26) {
    console.log(`  line ${lineno}: skipped — powerball out of range ${powerball}`);
    return null;
  }
  if (new Set(whites).size !== 5) {
    console.log(`  line ${lineno}: skipped — duplicate whites ${JSON.stringify(whites)}`);
    return null;
  }

  const drawDate = new Date(Date.UTC(year, month - 1, day));
  if (drawDate.getUTCFullYear() !== year || drawDate.getUTCMonth() !== month - 1 || drawDate.getUTCDate() !== day) {
    console.log(`  line ${lineno}: skipped — invalid date ${year}-${month}-${day}`);
    return null;
  }

  return {
    draw_date: drawDate.toISOString().slice(0, 10),
    n1: whites[0],
    n2: whites[1],
    n3: whites[2],
    n4: whites[3],
    n5: whites[4],
    powerball,
    multiplier,
  };
}

function parseCsv(filepath) {
  const text = fs.readFileSync(filepath, "utf-8").replace(/^﻿/, "");
  const lines = text.split(/\r?\n/);
  const seen = new Set();
  const rows = [];
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (!line.trim()) continue;
    const parsed = parseRow(parseCsvLine(line), i + 1);
    if (!parsed) continue;
    if (seen.has(parsed.draw_date)) continue;
    seen.add(parsed.draw_date);
    rows.push(parsed);
  }
  rows.sort((a, b) => a.draw_date.localeCompare(b.draw_date));
  return rows;
}

function pad(n, width) {
  return String(n).padStart(width, " ");
}

function writeSql(rows, outPath) {
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  const lines = [];
  lines.push(
    "-- ─────────────────────────────────────────────────────────────────────",
    "-- Million Mind — Full History Seed (generated by import_csv.mjs)",
    "-- ─────────────────────────────────────────────────────────────────────",
    "-- Generated from a Powerball CSV. Run AFTER applying the initial",
    "-- migration:",
    "--   supabase db reset                             (local)",
    "--   psql \"$DATABASE_URL\" -f supabase/seed/full_history.sql",
    "-- Idempotent — ON CONFLICT (draw_date) DO NOTHING.",
    "-- ─────────────────────────────────────────────────────────────────────",
    "",
  );

  const BATCH = 200;
  for (let i = 0; i < rows.length; i += BATCH) {
    const batch = rows.slice(i, i + BATCH);
    lines.push(
      "INSERT INTO public.drawings (draw_date, n1, n2, n3, n4, n5, powerball, multiplier) VALUES",
    );
    const valueLines = batch.map(
      (r) =>
        `    ('${r.draw_date}', ${pad(r.n1, 2)}, ${pad(r.n2, 2)}, ${pad(r.n3, 2)}, ${pad(r.n4, 2)}, ${pad(r.n5, 2)}, ${pad(r.powerball, 2)}, ${r.multiplier})`,
    );
    lines.push(valueLines.join(",\n"));
    lines.push("ON CONFLICT (draw_date) DO NOTHING;");
    lines.push("");
  }
  lines.push("SELECT public.refresh_number_stats();", "");

  fs.writeFileSync(outPath, lines.join("\n"), "utf-8");
}

function writeCsv(rows, outPath) {
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  const header = "draw_date,n1,n2,n3,n4,n5,powerball,multiplier";
  const body = rows
    .map((r) =>
      [r.draw_date, r.n1, r.n2, r.n3, r.n4, r.n5, r.powerball, r.multiplier].join(","),
    )
    .join("\n");
  fs.writeFileSync(outPath, `${header}\n${body}\n`, "utf-8");
}

function main() {
  const argv = process.argv.slice(2);
  const args = parseArgs(argv);
  const repoRoot = path.resolve(import.meta.dirname, "..", "..");
  const inputPath = resolveInput(args.input);
  const sqlOut = path.resolve(args.sql ?? path.join(repoRoot, "supabase", "seed", "full_history.sql"));
  const csvOut = path.resolve(args.csv ?? path.join(repoRoot, "supabase", "seed", "full_history.csv"));

  if (!fs.existsSync(inputPath)) {
    console.error(`ERROR: input file not found: ${inputPath}`);
    process.exit(1);
  }

  console.log(`\nReading: ${inputPath}`);
  const rows = parseCsv(inputPath);
  if (rows.length === 0) {
    console.error("ERROR: no valid rows parsed.");
    process.exit(1);
  }

  console.log(`  parsed ${rows.length} valid drawings`);
  console.log(`  date range: ${rows[0].draw_date} -> ${rows[rows.length - 1].draw_date}`);

  writeSql(rows, sqlOut);
  console.log(`\nWrote SQL: ${sqlOut}  (${rows.length} rows)`);

  writeCsv(rows, csvOut);
  console.log(`Wrote CSV: ${csvOut}  (${rows.length} rows)`);

  console.log("\nNext step:");
  console.log(`  psql "$DATABASE_URL" -f ${path.relative(process.cwd(), sqlOut).replace(/\\/g, "/")}`);
}

main();
